# Welcome to Jekyll!
#

# Site settings
title: Jacob Atchley
description: Blah
owner: Jacob Atchley
first_published: 2017
email: jacob.atchley@outlook.com
baseurl: "" 
url: "https://jacobatchley.github.io"
social:
  twitter: 
  github: https://github.com/jacobatchley
  linkedin-square: https://www.linkedin.com/in/jacobatchley/
  facebook-official: 
  google-plus-square: https://plus.google.com/u/0/+JacobAtchley1987
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
